######################################################################
# Automatically generated by qmake (3.0) ?? ???? 14 21:01:50 2016
######################################################################

QT += widgets
TEMPLATE = app
TARGET = TransparentClock
INCLUDEPATH += .

# Input
HEADERS += Clock.h
FORMS += ClockConfig.ui ClockSettings.ui
SOURCES += Clock.cpp Main.cpp
